'use client';

import { useState } from 'react';
import { db } from '@/lib/firebase'; // We still use Firestore for data!
import { collection, addDoc } from 'firebase/firestore';
// Firebase Storage imports are REMOVED
import { Plane, Tag, DollarSign, FileText, CheckCircle, PlusCircle, Loader2, Image as ImageIcon, UploadCloud } from 'lucide-react';

export default function AdminDashboard() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  
  const [formData, setFormData] = useState({
    destinationId: 'dxb',
    title: '',
    focus: '',
    price: '',
    tag: 'Bestseller'
  });
  
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setImageFile(file);
      setImagePreview(URL.createObjectURL(file));
    }
  };

  const handlePublish = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setShowSuccess(false);

    try {
      let imageUrl = '';

      // 1. NEW UPLOAD LOGIC: Send to our local Vercel Blob API Route
      if (imageFile) {
        // We create a unique filename using timestamp
        const uniqueFilename = `${Date.now()}-${imageFile.name}`;
        
        // Fetch our secure internal API
        const response = await fetch(
          `/api/upload?filename=${uniqueFilename}`,
          {
            method: 'POST',
            body: imageFile, // Send raw file body
          },
        );

        if (!response.ok) {
          throw new Error('Failed to upload image to Vercel Blob.');
        }

        const newBlob = await response.json();
        imageUrl = newBlob.url; // The public URL from Vercel Blob!
      }

      // 2. Save Data + New Vercel Blob URL to Firestore (Still using Firebase for DB)
      await addDoc(collection(db, 'packages'), {
        destinationId: formData.destinationId,
        title: formData.title,
        focus: formData.focus,
        price: formData.price,
        tag: formData.tag,
        imageUrl: imageUrl, // URL is now generated by Vercel
        status: 'active',
        createdAt: new Date()
      });
      
      // 3. Reset form
      setShowSuccess(true);
      setFormData({ ...formData, title: '', focus: '', price: '' });
      setImageFile(null);
      setImagePreview(null);
      
      setTimeout(() => setShowSuccess(false), 3000);
      
    } catch (error) {
      console.error("Error publishing package: ", error);
      alert("Failed to publish package. Ensure Vercel Blob token is set in .env.local.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans p-4 md:p-8">
      <div className="max-w-3xl mx-auto">
        
        <div className="bg-slate-900 rounded-3xl p-8 text-white mb-8 shadow-xl relative overflow-hidden">
          <div className="absolute top-0 right-0 -mr-16 -mt-16 w-48 h-48 bg-[#00b4a9] rounded-full opacity-20 blur-3xl"></div>
          <h1 className="text-3xl font-black mb-2 relative z-10">Luma Command Center</h1>
          <p className="text-slate-400 text-sm relative z-10">Deploy new travel packages with Vercel native image hosting.</p>
        </div>

        <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-8">
          <div className="flex items-center mb-8 pb-4 border-b border-slate-100">
            <div className="w-10 h-10 rounded-full bg-teal-50 flex items-center justify-center mr-4">
              <PlusCircle className="w-5 h-5 text-[#00b4a9]" />
            </div>
            <h2 className="text-xl font-bold text-slate-800">Create New Package</h2>
          </div>

          <form onSubmit={handlePublish} className="space-y-6">
            
            {/* Image Upload Section */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Package Thumbnail (Vercel Native)</label>
              <div className="border-2 border-dashed border-slate-200 rounded-2xl p-6 flex flex-col items-center justify-center bg-slate-50 relative hover:bg-slate-100 transition-colors cursor-pointer group">
                <input 
                  type="file" 
                  accept="image/*"
                  onChange={handleImageChange}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-20"
                />
                
                {imagePreview ? (
                  <div className="relative w-full h-48 rounded-xl overflow-hidden shadow-sm">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" />
                    <div className="absolute inset-0 bg-slate-900/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                      <p className="text-white font-bold flex items-center"><UploadCloud className="w-5 h-5 mr-2"/> Change Image</p>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-6">
                    <div className="w-16 h-16 bg-white rounded-full shadow-sm flex items-center justify-center mx-auto mb-4 text-[#00b4a9]">
                      <ImageIcon className="w-8 h-8" />
                    </div>
                    <p className="font-bold text-slate-700">Click to upload or drag and drop</p>
                    <p className="text-xs text-slate-400 mt-1">PNG, JPG, WebP up to 5MB</p>
                  </div>
                )}
              </div>
            </div>

            {/* Target Destination */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Target Hub</label>
              <div className="relative">
                <Plane className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" />
                <select 
                  className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-700 focus:outline-none focus:border-[#00b4a9] focus:ring-1 focus:ring-[#00b4a9] appearance-none"
                  value={formData.destinationId}
                  onChange={(e) => setFormData({...formData, destinationId: e.target.value})}
                >
                  <option value="dxb">Dubai, UAE</option>
                  <option value="my">Malaysia</option>
                  <option value="sg">Singapore</option>
                  <option value="th">Thailand</option>
                  <option value="cn">China</option>
                </select>
              </div>
            </div>

            {/* Package Title */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Package Title</label>
              <div className="relative">
                <FileText className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" />
                <input 
                  type="text"
                  required
                  placeholder="e.g. Dubai Family Getaway"
                  className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-800 placeholder:text-slate-400 focus:outline-none focus:border-[#00b4a9] focus:ring-1 focus:ring-[#00b4a9]"
                  value={formData.title}
                  onChange={(e) => setFormData({...formData, title: e.target.value})}
                />
              </div>
            </div>

            {/* Package Focus / Description */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Key Highlights / Focus</label>
              <div className="relative">
                <FileText className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" />
                <input 
                  type="text"
                  required
                  placeholder="e.g. Theme Parks, Wildlife & Resorts"
                  className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-800 placeholder:text-slate-400 focus:outline-none focus:border-[#00b4a9] focus:ring-1 focus:ring-[#00b4a9]"
                  value={formData.focus}
                  onChange={(e) => setFormData({...formData, focus: e.target.value})}
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Price */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Starting Price</label>
                <div className="relative">
                  <DollarSign className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" />
                  <input 
                    type="text"
                    required
                    placeholder="e.g. Rs. 245,000"
                    className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-800 placeholder:text-slate-400 focus:outline-none focus:border-[#00b4a9] focus:ring-1 focus:ring-[#00b4a9]"
                    value={formData.price}
                    onChange={(e) => setFormData({...formData, price: e.target.value})}
                  />
                </div>
              </div>

              {/* Tag */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Marketing Tag</label>
                <div className="relative">
                  <Tag className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" />
                  <select 
                    className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-700 focus:outline-none focus:border-[#00b4a9] focus:ring-1 focus:ring-[#00b4a9] appearance-none"
                    value={formData.tag}
                    onChange={(e) => setFormData({...formData, tag: e.target.value})}
                  >
                    <option value="Bestseller">Bestseller</option>
                    <option value="Luxury">Luxury</option>
                    <option value="Extended">Extended</option>
                    <option value="Trending">Trending</option>
                  </select>
                </div>
              </div>
            </div>

            {/* Submit Button */}
            <div className="pt-6 border-t border-slate-100 mt-8 flex items-center justify-between">
              {showSuccess ? (
                <div className="flex items-center text-[#00b4a9] font-bold text-sm animate-in fade-in slide-in-from-left-4 duration-300">
                  <CheckCircle className="w-5 h-5 mr-2" /> Live in Database!
                </div>
              ) : (
                <div></div>
              )}
              
              <button 
                type="submit" 
                disabled={isSubmitting}
                className="bg-gradient-to-r from-[#00b4a9] to-[#009bd6] text-white px-8 py-3.5 rounded-xl font-black shadow-lg hover:brightness-110 transition-all flex items-center disabled:opacity-70 disabled:cursor-not-allowed"
              >
                {isSubmitting ? (
                  <><Loader2 className="w-5 h-5 mr-2 animate-spin" /> Publishing...</>
                ) : (
                  'Deploy Package (Blob)'
                )}
              </button>
            </div>

          </form>
        </div>
      </div>
    </div>
  );
}